/* Generated By:JJTree: Do not edit this line. ASTVARS.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal2jvm.ast;

public class ASTARGUMENTS extends SimpleNode
{

	public ASTARGUMENTS(int id)
	{
		super(id);
	}

	public ASTARGUMENTS(YalParser p, int id)
	{
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=c86e594baa7caafd8095257e87157902 (do not edit this
 * line)
 */
