/* Generated By:JJTree: Do not edit this line. ASTDECLARATION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal2jvm.ast;

public class ASTDECLARATION extends SimpleNode
{

	public String operator = "";
	public Integer integer = null;

	public ASTDECLARATION(int id)
	{
		super(id);
	}

	public ASTDECLARATION(YalParser p, int id)
	{
		super(p, id);
	}

	public void dump(String prefix)
	{
		System.out.println(toString(prefix));
		if (children == null)
		{
			if (this.integer != null)
				System.out.println(prefix + "\"" + this.operator + this.integer + "\"");
		}
		if (children != null)
		{
			if (this.integer != null)
				System.out.println(prefix + "\"" + this.operator + this.integer + "\"");
			for (Node aChildren : children)
			{
				SimpleNode n = (SimpleNode) aChildren;
				if (n != null)
				{
					n.dump(prefix + " ");
				}
			}
		}
	}
}
/*
 * JavaCC - OriginalChecksum=15e484f6685479de829a265fe7dc2264 (do not edit this
 * line)
 */
