/* Generated By:JJTree: Do not edit this line. ASTEXPRTEST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal2jvm.ast;

public class ASTEXPRTEST extends SimpleNode
{

	public String operation;

	public ASTEXPRTEST(int id)
	{
		super(id);
	}

	public ASTEXPRTEST(YalParser p, int id)
	{
		super(p, id);
	}

	public void dump(String prefix)
	{
		System.out.println(toString(prefix));
		if (children == null)
		{
			System.out.println(prefix + "\"" + this.operation + "\"");
		}
		if (children != null)
		{
			if (!this.operation.equals(""))
				System.out.println(prefix + "\"" + this.operation + "\"");
			for (Node aChildren : children)
			{
				SimpleNode n = (SimpleNode) aChildren;
				if (n != null)
				{
					n.dump(prefix + " ");
				}
			}
		}
	}

}
/*
 * JavaCC - OriginalChecksum=36536559df5438e881ab911851494c63 (do not edit this
 * line)
 */
