/* Generated By:JJTree: Do not edit this line. ASTINDEX.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal2jvm.ast;

public class ASTINDEX extends SimpleNode
{

	public String indexID;
	public Integer indexValue;

	public ASTINDEX(int id)
	{
		super(id);
	}

	public ASTINDEX(YalParser p, int id)
	{
		super(p, id);
	}

	public void dump(String prefix)
	{
		System.out.println(toString(prefix));
		if (children == null)
		{
			if (this.indexID != null)
				System.out.println(prefix + "\"" + this.indexID + "\"");
			if (this.indexValue != null)
				System.out.println(prefix + "\"" + this.indexValue + "\"");
		}
		if (children != null)
		{
			if (this.indexID != null)
				System.out.println(prefix + "\"" + this.indexID + "\"");
			if (this.indexValue != null)
				System.out.println(prefix + "\"" + this.indexValue + "\"");
			for (Node aChildren : children)
			{
				SimpleNode n = (SimpleNode) aChildren;
				if (n != null)
				{
					n.dump(prefix + " ");
				}
			}
		}
	}
}
/*
 * JavaCC - OriginalChecksum=b3d757b886bb47f4c6cbd2218ec57c04 (do not edit this
 * line)
 */
