/* Generated By:JJTree: Do not edit this line. ASTMODULE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal2jvm.ast;

public class ASTMODULE extends SimpleNode
{

	public String name = "";

	public ASTMODULE(int id)
	{
		super(id);
	}

	public ASTMODULE(YalParser p, int id)
	{
		super(p, id);
	}

	public void dump(String prefix)
	{
		System.out.println(toString(prefix));
		if (children == null)
		{
			System.out.println(prefix + "\"" + this.name + "\"");
		}
		if (children != null)
		{
			if (!this.name.equals(""))
				System.out.println(prefix + "\"" + this.name + "\"");
			for (Node aChildren : children)
			{
				SimpleNode n = (SimpleNode) aChildren;
				if (n != null)
				{
					n.dump(prefix + " ");
				}
			}
		}
	}
}
/*
 * JavaCC - OriginalChecksum=d06ebfcdfe6c92b64e4b9ca8c0fba3d3 (do not edit this
 * line)
 */
